Repository InsertKoinIO/koin, pull requests merged in 2020-05, with the labels that each got.

#779 Updated "applicationContext" to "module" in documentation
  koin-projects/docs/start/getting-started/koin-for-android.md
Labels: type:documentation

#781 Disable property type cast to fix issue gh-291
  koin-projects/examples/android-samples/src/main/java/org/koin/sample/android/mvvm/MVVMActivity.kt
  koin-projects/examples/android-samples/src/main/java/org/koin/sample/android/mvvm/MVVMFragment.kt
  koin-projects/examples/androidx-samples/src/main/java/org/koin/sample/androidx/mvvm/MVVMActivity.kt
  koin-projects/examples/androidx-samples/src/main/java/org/koin/sample/androidx/mvvm/MVVMFragment.kt
  koin-projects/koin-core/src/main/kotlin/org/koin/core/Koin.kt
  koin-projects/koin-core/src/main/kotlin/org/koin/core/KoinApplication.kt
  koin-projects/koin-core/src/main/kotlin/org/koin/core/registry/PropertyRegistry.kt
  koin-projects/koin-core/src/main/kotlin/org/koin/core/scope/Scope.kt
  koin-projects/koin-core/src/main/kotlin/org/koin/ext/KoinPropertyExt.kt
  koin-projects/koin-core/src/main/kotlin/org/koin/ext/StringExt.kt
  koin-projects/koin-core/src/test/java/org/koin/dsl/EnvironmentPropertyDefinitionTest.kt
  koin-projects/koin-core/src/test/java/org/koin/dsl/FilePropertyDefinitionTest.kt
  koin-projects/koin-core/src/test/java/org/koin/dsl/PropertyDefinitionTest.kt
  koin-projects/koin-ktor/src/main/kotlin/org/koin/ktor/ext/KtorApplicationExt.kt
  koin-projects/koin-ktor/src/main/kotlin/org/koin/ktor/ext/KtorRouteExt.kt
  koin-projects/koin-ktor/src/main/kotlin/org/koin/ktor/ext/KtorRoutingExt.kt
Labels: koin-core, status:accepted, team:open-contribution

#773 support declare a component definition with primary type
  koin-projects/koin-core/src/main/kotlin/org/koin/core/definition/Definitions.kt
  koin-projects/koin-core/src/main/kotlin/org/koin/core/scope/Scope.kt
  koin-projects/koin-core/src/main/kotlin/org/koin/core/scope/ScopeDefinition.kt
  koin-projects/koin-core/src/test/java/org/koin/core/DeclareInstanceTest.kt
Labels: status:accepted, team:open-contribution
