Repository InsertKoinIO/koin, pull requests merged in 2021-11, with the labels that each got.

#1186 Add `resolve` API to auto resolve constructors with no reflection
  core/koin-core/src/commonMain/kotlin/org/koin/core/scope/ScopeExt.kt
Labels: core, status:accepted, type:feature-proposal

#1170 docs: add missing space
  docs/setup/v3.md
Labels: documentation

#1160 Update scope.md
  docs/reference/koin-android/scope.md
Labels: documentation

#1152 Fix typo
  docs/reference/koin-test/testing.md
Labels: documentation

#1169 fix typo and update sentence
  docs/quickstart/android.md
Labels: documentation

#1166 Add BeanDefinition to ScopedInstance error message
  core/koin-core/src/commonMain/kotlin/org/koin/core/instance/ScopedInstanceFactory.kt
Labels: core, status:checking

#1155 Fix safe access in Context Isolation docs
  docs/reference/koin-core/context-isolation.md
Labels: status:checking, documentation

#1175 KoinJavaComponent.kt update to make it able to return null values.
  core/koin-core/src/jvmMain/kotlin/org/koin/java/KoinJavaComponent.kt
Labels: core, status:checking

#1192 Add Support for Apple Silicon
  core/koin-core/build.gradle
  core/koin-test/build.gradle
Labels: core, status:accepted, kmm

#1234 Update v3.md
  docs/setup/v3.md
Labels: documentation
